version: '3.8'

services:
  app:
    build: .
    container_name: notification-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_database
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./src:/app/src
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: notification-db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
